[metadata]
name = table-ocr-app
version = 0.1.0

[options]
packages = find:
package_dir =
	=src
install_requires =
	opencv-python-headless
	numpy
	Pillow
	pytesseract
	pandas
	openpyxl
	scikit-image
	scipy
	rich
	PyYAML

[options.extras_require]
ui =
	PySide6
ocr =
	easyocr

[options.packages.find]
where = src

[options.entry_points]
console_scripts =
	table-ocr-cli = table_ocr_app.cli:main
	table-ocr-gui = table_ocr_app.qt_app:main